name: Deploy to GitHub Pages

on:
  push:
    tags:
     - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create gh_pages
        uses: christopherdavenport/create-ghpages-ifnotexists@v1
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/gh-pages